services:
  backend: 
    container_name: "avalicaco_backend"
    image: backend 
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      
volumes:
  postgres-volume: