CREATE TABLE evaluations (
  id SERIAL PRIMARY KEY,
  title VARCHAR NOT NULL,
  class TEXT NOT NULL,
  date TIMESTAMP NOT NULL
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  login VARCHAR UNIQUE NOT NULL ,
  password_hash VARCHAR NOT NULL
)

